apiVersion: v1
kind: Service
metadata:
  name: {{ include "netgear-metrics.fullname" . }}
  labels:
    {{- include "netgear-metrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: metrics-port
  selector:
    {{- include "netgear-metrics.selectorLabels" . | nindent 4 }}
