apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-router-auth
data:
  url: {{ .Values.routerLogin.url | b64enc }}
  password: {{ .Values.routerLogin.password | b64enc }}
  username: {{ .Values.routerLogin.username | b64enc }}