{{- if .Values.serviceMonitor.enabled -}}
{{- $fullName := include "netgear-metrics.fullname" . -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "netgear-metrics.labels" . | nindent 4 }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}    
spec:
  selector:
    matchLabels:
      {{- include "netgear-metrics.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics-port
    interval: {{ .Values.serviceMonitor.interval | quote }}
    path: /metrics
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | quote }}
{{- end -}}