name: Release Chart

on:
  push:
    branches:
      - gh-pages

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout multiple repos (nested)
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ConnorsApps/netgear-nighthawk-metrics
          path: charts/

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"